//! Generated source and provenance models.

use disassembler::{AddressRange, FunctionCoordinate};
use mlil::InstructionId;

use crate::Diagnostic;

/// Half-open UTF-8 byte range in generated Java source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct GeneratedSpan {
    /// Inclusive generated byte offset.
    pub start: usize,
    /// Exclusive generated byte offset.
    pub end: usize,
}

/// Generated Java range mapped back through MLIL to native bytecode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceMapEntry {
    /// Generated source range.
    pub generated: GeneratedSpan,
    /// Overload- and format-qualified native function coordinate.
    pub function: FunctionCoordinate,
    /// Stable semantic instruction identity.
    pub instruction: InstructionId,
    /// Every native bytecode range contributing to the instruction.
    pub native_ranges: Vec<AddressRange>,
}

/// One Java method body recovered from an MLIL function.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecompiledBody {
    /// Body statements without the surrounding method braces.
    pub source: String,
    /// Non-fatal recovery diagnostics.
    pub diagnostics: Vec<Diagnostic>,
    /// Generated-to-native provenance relative to [`Self::source`].
    pub source_map: Vec<SourceMapEntry>,
}

/// Complete Java compilation unit recovered from one JVM class file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecompiledClass {
    /// Generated Java compilation unit.
    pub source: String,
    /// Non-fatal declaration and method diagnostics.
    pub diagnostics: Vec<Diagnostic>,
    /// Generated-to-native provenance relative to [`Self::source`].
    pub source_map: Vec<SourceMapEntry>,
}
